modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Illegal-Building/issues"
license="MIT"

[[mods]]
modId="illegalbuilding"
version="${file.jarVersion}"
displayName="Illegal Building"
displayURL="https://www.curseforge.com/minecraft/mc-mods/illegal-building"
authors="Mrbysco"
description='''
Just some blasphemy.
'''
[[dependencies.illegalbuilding]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.illegalbuilding]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"