modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/Illegal-Building/issues"
license="MIT"

[[mods]]
modId="illegalbuilding"
version="${file.jarVersion}"
displayName="Illegal Building"
displayURL="https://www.curseforge.com/minecraft/mc-mods/illegal-building"
authors="Mrbysco"
description='''
Just some blasphemy.
'''
[[dependencies.illegalbuilding]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"