modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Illegal-Building/issues"
license="MIT"

[[mods]]
modId="illegalbuilding"
version="${file.jarVersion}"
displayName="Illegal Building"
displayURL="https://www.curseforge.com/minecraft/mc-mods/illegal-building"
authors="Mrbysco"
description='''
Just some blasphemy.
'''
[[dependencies.illegalbuilding]]
modId="minecraft"
type="required"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.illegalbuilding]]
modId="neoforge"
type="required"
versionRange="[26.1.1.0-alpha,)"
ordering="NONE"
side="BOTH"